--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackMD/MysteryCrate
branches:
- master
projects:
  MysteryCrate:
    path: ""
    lint: false
    icon: meta/MysteryCrate.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.6.5
...
