--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WavyCraftNetwork/MysteryCrate
build-by-default: true
branches:
- master
projects:
  MysteryCrate:
    path: ""
    libs:
      - src: "Muqsit/InvMenu/InvMenu"
        branch: pm5
        version: ^4.6.5
...
