name: MysteryCrate
main: JackMD\MysteryCrate\Main
api: 5.3.0
version: 1.0.0
author: JackMD
authors: [DaPigGuy, WavyCraftNetwork, Terpz710]
load: POSTWORLD
description: Add unlimited number of MysteryCrates with full customization.
website: https://github.com/WavyCraftNetwork/MysteryCrate

permissions:
 mc.crates.use:
  default: true
  description: "Allows using the crates."
 mc.command.key:
  default: op
  description: "Allows use of /key command."
 mc.command.keyall:
   default: op
   description: "Allows using /keyall command."
 mc.crates.create:
  default: op
  description: "Allows using the crates."
 mc.crates.destroy:
  default: op
  description: "Allows using the crates."
